bind_to_address = "127.0.0.1"
block_size = 64
load_synth_defs = true
max_interconnect_buffers = 64
max_logins = 64
max_nodes = 1024
max_synth_defs = 1024
num_audio_bus_channels = 1024
num_buffers = 1024
num_control_bus_channels = 16384
num_input_bus_channels = 8
num_output_bus_channels = 8
path = "/Applications/SuperCollider.app/Contents/Resources/scsynth"
preferred_hardware_buffer_size = 512
preferred_sample_rate = 44100
publish_to_rendezvous = true
random_number_generators = 64
real_time_memory_size = 8192
tcp_port_number = 4242
udp_port_number = 0
verbosity = 0
